### ISSUE TITLE
ValueError: Unable to configure handler 'syslog': [Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by alexcg1** [newtonproject/newton-www#2]
On the final step of README.md, I get the following error

```
~/newton-www/web# ./environment/test/testing.sh
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/newton-www/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line                 
    utility.execute()
  File "/root/newton-www/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute                                   
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/newton-www/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command                             
    commands = get_commands()
  File "/root/newton-www/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands                              
    apps = settings.INSTALLED_APPS
  File "/root/newton-www/ve/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__                                           
    self._setup(name)
  File "/root/newton-www/ve/local/lib/python2.7/site-packages/django/conf/__init__.py", line 50, in _setup                                                
    self._configure_logging()
  File "/root/newton-www/ve/local/lib/python2.7/site-packages/django/conf/__init__.py", line 80, in _configure_logging                                    
    logging_config_func(self.LOGGING)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'syslog': [Errno 2] No such file or directory

**Comment by alexcg1** [comment]
(The reason I'm trying to run locally is because translation team want before/after versions of the text, and IMHO cleanest way to do that is by loading the Django site into browser and capturing the output HTML)

**Comment by xiawu** [comment]
what's your OS version?

**Comment by alexcg1** [comment]
Ubuntu 18.04, running in docker

**Comment by alexcg1** [comment]
As temporary fix, disabling logging makes it start okay: https://docs.djangoproject.com/en/2.1/topics/logging/#disabling-logging-configuration

**Comment by xiawu** [comment]
@alexcg1 i have comment the syslog configuration. i think for local testing, syslog is not necessary

**Comment by Anthony-genius** [comment]
You should check whether your database server(such as mysql Server and so on) is installed on your PC or not.
If not you should install db server.
